version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: oliolaina/kittygram_backend
    env_file: .env
    depends_on:
      - db
    command: sh -c "until python -c \"import os, psycopg2; psycopg2.connect(host=os.getenv('DB_HOST', 'db'), port=os.getenv('DB_PORT', '5432'), dbname=os.getenv('POSTGRES_DB'), user=os.getenv('POSTGRES_USER'), password=os.getenv('POSTGRES_PASSWORD')).close()\"; do echo 'Waiting for postgres...'; sleep 2; done && echo 'PostgreSQL is ready' && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8000 kittygram_backend.wsgi"
    volumes:
      - static:/app/static
      - media:/app/media

  frontend:
    image: oliolaina/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    image: oliolaina/kittygram_gateway
    depends_on:
      - backend
      - frontend
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media
